<?php

use Inertia\Inertia;
use Illuminate\Support\Facades\Route;

// Home Page
Route::get('/', function () {
    return Inertia::render('Home');
});

// Catalogue
Route::get('/catalogue', function () {
    return Inertia::render('Catalogue');
});

// Brand Page (Dynamic)
Route::get('/catalogue/{brand}', function ($brand) {
    return Inertia::render('Brand', [
        'brandName' => $brand
    ]);
});

// Product Page (Dynamic)
Route::get('/catalogue/{brand}/{product}', function ($brand, $product) {
    return Inertia::render('Product', [
        'brand' => $brand,
        'product' => $product
    ]);
});

// Profile
Route::get('/profile/{id}', function ($id) {
    return Inertia::render('Profile', ['id' => $id]);
});

// Include the Auth routes (Login/Register) generated by Breeze
require __DIR__.'/auth.php';